### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by mad-coder-365** [Meteor-Community-Packages/meteor-user-status#153]
On a brand new project after doing `meteor create`,

I added user-status -- `meteor add mizzao:user-status`

It fails to install it. I keep getting this error: 

```
 => Errors while adding packages:             
                                              
While loading package mizzao:user-status@1.0.1:
error: Command failed: /Users/test/.meteor/packages/meteor-tool/.2.7.1.bn3d8n.ijpv8++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/npm rebuild
--update-binary
env: python: No such file or directory
make: *** [Release/nothing.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/Users/test/.meteor/packages/meteor-tool/.2.7.1.bn3d8n.ijpv8++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/Users/test/.meteor/packages/meteor-tool/.2.7.1.bn3d8n.ijpv8++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/node"
"/Users/test/.meteor/packages/meteor-tool/.2.7.1.bn3d8n.ijpv8++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"build" "--fallback-to-build"
"--module=/Users/test/.meteor/packages/mizzao_user-status/.1.0.1.7i5kyi.bo2e++os+web.browser+web.browser.legacy+web.cordova/npm/demo/node_modules/.temp-c29yxl.vg0mp/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node"
"--module_name=bcrypt_lib"
"--module_path=/Users/test/.meteor/packages/mizzao_user-status/.1.0.1.7i5kyi.bo2e++os+web.browser+web.browser.legacy+web.cordova/npm/demo/node_modules/.temp-c29yxl.vg0mp/node_modules/bcrypt/lib/binding/napi-v3"
"--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /Users/test/.meteor/packages/mizzao_user-status/.1.0.1.7i5kyi.bo2e++os+web.browser+web.browser.legacy+web.cordova/npm/demo/node_modules/.temp-c29yxl.vg0mp/node_modules/bcrypt
gyp ERR! node -v v14.19.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute
'/Users/test/.meteor/packages/meteor-tool/.2.7.1.bn3d8n.ijpv8++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/node
/Users/test/.meteor/packages/meteor-tool/.2.7.1.bn3d8n.ijpv8++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
build --fallback-to-build
--module=/Users/test/.meteor/packages/mizzao_user-status/.1.0.1.7i5kyi.bo2e++os+web.browser+web.browser.legacy+web.cordova/npm/demo/node_modules/.temp-c29yxl.vg0mp/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
--module_name=bcrypt_lib
--module_path=/Users/test/.meteor/packages/mizzao_user-status/.1.0.1.7i5kyi.bo2e++os+web.browser+web.browser.legacy+web.cordova/npm/demo/node_modules/.temp-c29yxl.vg0mp/node_modules/bcrypt/lib/binding/napi-v3
--napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous>
(/Users/test/.meteor/packages/mizzao_user-status/.1.0.1.7i5kyi.bo2e++os+web.browser+web.browser.legacy+web.cordova/npm/demo/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Darwin 21.4.0
node-pre-gyp ERR! command "/Users/test/.meteor/packages/meteor-tool/.2.7.1.bn3d8n.ijpv8++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/node"
"/Users/test/.meteor/packages/mizzao_user-status/.1.0.1.7i5kyi.bo2e++os+web.browser+web.browser.legacy+web.cordova/npm/demo/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd
/Users/test/.meteor/packages/mizzao_user-status/.1.0.1.7i5kyi.bo2e++os+web.browser+web.browser.legacy+web.cordova/npm/demo/node_modules/.temp-c29yxl.vg0mp/node_modules/bcrypt
node-pre-gyp ERR! node -v v14.19.1
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test/.npm/_logs/2022-04-02T05_59_18_457Z-debug.log

```
I have not installed any package. 

Meteor version: Meteor 2.7.1
Node version: v16.14.2
Laptop: M1 Mac Pro

**Comment by BilalSonmez** [comment]
I have same issues in M1 Macbook Pro

**Comment by mad-coder-365** [comment]
@BilalSonmez Thanks a ton! It worked for me also :)

**Comment by BilalSonmez** [comment]
> @BilalSonmez Thanks a ton! It worked for me also :)

U're Welcome 😄
