### ISSUE TITLE
MongoDB throws an error at startup

### ISSUE THREAD

**Issue by reduxdj** [Meteor-Community-Packages/meteor-user-status#91]
MongoError: cannot use the part (status of status.online) to traverse the element ({status: "[object Object]"})
    at Object.Future.wait (/opt/parooz/app/programs/server/node_modules/fibers/future.js:398:15)
    at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:736:1)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)
    at Object.collection.(anonymous function) [as update](packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update](packages/aldeed_collection2/packages/aldeed_collection2.js:195:1)
    at onStartup (packages/mizzao_user-status/status.coffee:102:16)
    at /opt/parooz/app/programs/server/boot.js:249:5

The problem seems to be related to the schema I am using:
onStartup = (selector = {}) ->
  Meteor.users.update selector,
    {
      $set: {
        "status.online": false
      },
      $unset: {
        "status.idle": null
        "status.lastActivity": null
      }
    },
    { multi: true }

  #   },
  #   { multi: true }

Using collection2:

  'status.lastLogin.date':
    type: Date
    optional: true
  'status.lastLogin.ipAddr':
    type: String
    optional: true
  'status.userAgent':
    type: String
    optional: true
  'status.idle':
    type: Boolean
    optional: true
    blackbox: true
  'status.lastActivity':
    type: Date
    optional: true
  'status.online':
    type: Boolean
    index: true
    optional: true

Looks like for whatever reason that stutus is an array, rather than an object... because of the mongo error
trying to update an array where an object should be:

http://stackoverflow.com/questions/23821392/how-to-update-value-of-a-key-in-a-list-of-a-json-in-mongo

commenting out the onStartup block works for me - for the time being

**Comment by dgroch** [comment]
I've been experiencing the same issue. 
For the moment I've commented out the code

```

if (Meteor.isServer){
  // Adds default status to prevent malformed data issues
  Accounts.onCreateUser(function(options, user){
    user.status = {
      online: false
    };
    if (options.profile)
      user.profile = options.profile;
    return user;
  });
};
```

But wondering what the solution is?

**Comment by pociej** [comment]
+1

**Comment by riiiiizzzzzohmmmmm** [comment]
+1

**Comment by mizzao** [comment]
Is this an issue because you guys are using collection2 with an incorrect schema? If so, see #60.
